version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: my_postgres_container
    ports:
      - "${DB_PORT}:5432"
    #volumes:
    # - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
